server:
  port: 8080
  servlet:
    context-path: "/api/todoapp/postgres"

spring:
  application:
    name: todoapp
  datasource:
    username: postgres_user
    password: SuperSecret
    url: jdbc:postgresql://localhost:5432/todoappdb
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS

  logging:
    level:
      root: INFO
      org.springframework.web: ERROR
      org.hibernate: ERROR
      com.demo.todoapi: DEBUG


